/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'start'
    }
  ],
  buildSidebar: [
    {
      type: 'autogenerated',
      dirName: 'build'
    }
  ],
  standardSidebar: [
    {
      type: 'category',
      label: 'Standards',
      collapsed: false,
      collapsible: false,
      items: [
        {
          type: 'doc',
          id: 'standards/readme',
          label: 'Welcome',
        },
        {
          type: 'category',
          label: 'Fungible Token',
          items: [
            {
              type: 'doc',
              id: 'standards/TIP-3/core-description',
              label: 'Basic',
            },
            {
              type: 'doc',
              id: 'standards/TIP-3/1',
              label: 'TIP-3.1',
            },
            {
              type: 'doc',
              id: 'standards/TIP-3/2',
              label: 'TIP-3.2',
            },
          ],
        },
        {
          type: 'doc',
          id: 'standards/TIP-3/core-description',
          label: 'Non-Fungible Token',
        },
      ]
    },
  ],
};

module.exports = sidebars;
